# Site settings
title: Shannon Fan's CV 
description: Shannon Fan's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ShannonFan.github.io/resumecard
url: https://ShannonFan.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Shannon Fan
  title: Graduate Student at University of Michigan, Ann Arbor
  address: Ann Arbor, Michigan
  email: xiaoy@umich.edu
  link: https://ShannonFan.github.io/resumecard
  weibo:
  github: ShannonFan
  linkedin: xiaoxiao-fan-5a8b839b
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: HSBC(Hong Kong and Shanghai Banking Coporate)
      location: Shanghai, China
      title: Summer Intern, Commercial Banking (CMB)
      started: 2016
      duration: (2016.7 - 2016.8)
      description: 1. Presented new structured investment products (SIPs) with PPT slides of clear facts and charts to support relation managers to launch new SIPs pilot program and sales campaign. Worked with relation managers to follow 20+ sales pipelines. 2.Created an Excel tool to calculate customers’ monthly transaction volume and value by a click, reducing the time of relation managers in our team when reviewing customer profiles. 3. Delivered daily morning briefing, summarizing global financial data and news from various resources to keep RMs informed of market trends. 4. Conducted a research on 100+ corporate financial products of HSBC’s major competitors to prepare for new product launching.
    - work2:
      company: DELOITTE
      location: Shanghai, China
      title: Risk Analyst Intern, Enterprise Risk Services
      started: 2016
      duration: (2016.6)
      description: 1. Worked with senior consultants to frame business risks for a client (a trust company) through client interviews, business unit researches and performance assessment (using models like RAROC). Draft PPT slides for the diagnostic report presentation. 2. Conducted benchmark analysis to propose solutions. 3. Analyzed regional growth data and high net worth individual resources to identify niche market, helping the client to launch a new wealth management business line.  4. Attended managers’ meeting and scribed notes to better scope the client’s ambition.
    - work3:
      company: WEBER SHANDWICK
      location: Beijing, China
      title: Public Relations Consultant Intern, Finance and Corporate Team
      started: 2014
      duration: (2014.9 - 2014.10)
      description: 1. Collected and analyzed media coverage data for a client and its major competitors. Completed media coverage reports and competitor analysis reports to identify brand awareness trend as well as track audience’s reaction to some certain events. 2. Extracted key information and drafted storylines of two commercial real estate projects to prepare a client for press meeting. 3.Assisted in delivering an annual report release for a client by enlisting influential financial media and bloggers to drive conversation.
  studentActivity:
    - activity1:
      organization: Vision Center, Tsinghua University
      location: Beijing, China
      title: Director
      started: 2014
      duration: (2014.9 - 2015.6)
      description: "1. Delivered publicity training lectures for students in Tsinghua University. My PPT training handouts drove conversation and were reposted by social media platforms of People’s Daily and LinkedIn China, with over 100,000 page views.                                                                                                                                      2. Led 10+ designers and 10+ photographers to plan and initiate a series of creative photos “a miniature campus,” which were widely reposted and helped build Tsinghua image, with over 30,000 page views. Drove Vision Center to become the inspiration of Tsinghua."
    - activity2:
      organization: Director, Event Planning Department , Student Association for Science and Technology, Tsinghua University
      location: Beijing, China
      title: Director
      started: 2013
      duration: (2013.9 - 2014.6)
      description: 1. Planned and prepared the 32nd Tsinghua University “Challenge Cup” Student Science & Technology Works Exhibition (the largest-scale extracurricular academic activity at THU) and attracted 6000+ visitors, presenting leading student academic works to the whole society and connecting students with businesses. Secured a sponsorship of USD 50,000 for this exhibition. 2.Worked together with 20+ event planning department members and 100+ on-spot student volunteers to coordinate 44 exhibitors (including student presenters as well as the representatives from Toshiba, Huawei, EMC, and Intel) and to serve visitors. 
  educationHistory:
    - education1:
      organization: University of Michigan, Ann Arbor
      location: Ann Arbor, Michigan, United States
      degree: Master
      major: Applied Economics
      started: 2015
      duration: (2015.9 - 2016.12)
      description: Course Highlights - Quantative Methods, Financial Derivatives, Big Data Analysis, Econometrics, Statistics for Finance Data, Accounting Principles, Project Management
    - education2:
      organization: Tsinghua University
      location: Beijing, China
      degree: Bachelor
      major: English Language and Literature
      started: 2011
      duration: (2011.9 - 2015.7)
      description: With a dual Bachelor's degree in Economics. Obtained Certificate of Test for English Majors-Band 8.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Fluent
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Microsoft Office
      percentage: 100%
    - skill2:
      name: Quantative Analytics (Using Stata and R)
      percentage: 100%
    - skill3: 
      name: Data Visualizatin
      percentage: 100%
    - skill4: 
      name: Communication and Storytelling
      percentage: 100%
    - skill5:
      name: Graphic Design (Using Adobe Photoshop)
      percentage: 100%
    - skill6:
      name: Music and Performance
      percentage: 100%
